### ISSUE TITLE
configure file not exist

### ISSUE THREAD

**Issue by akapucu** [sleinen/samplicator#29]
I can not see configure file

**Comment by tneuville** [comment]
same here - no configure script in the listings of the files in either this or the main branch.

**Comment by colebrumley** [comment]
This issue is preventing me from moving https://registry.hub.docker.com/u/elcolio/samplicator/ to target this repo instead :)

**Comment by twopoint71** [comment]
I don't know how to make a configure file, but I put this shell script together for compiling samplicator.
You will see some warnings, but they can be ignored as the binary still works in the end when all the object files are linked.

Run the file in the same directory the you **git cloned**
The resulting binary is named **samplicate**
```
#!/bin/bash
# file: compile-samplicate.sh
# date: 26-mar-2015
# auth: twopoint71
# info: compile samplicator

if [ ! -e config.h ]
   then
      cp acconfig.h config.h
   fi
   
if [ ! -e rawsend.c.bak ]
   then
      mv rawsend.c rawsend.c.bak
   fi
   
# fix a redeclaration error which prevents compiling
sed 's/int flags = 0;/flags = 0;/' ./rawsend.c.bak > ./rawsend.c

awk '
   $1 ~ /samplicate_SOURCES/ {
      split($0,files," ");
      for(key in files) {
         if(files[key] ~ /\.c$/) {
            printf("%s\n",files[key]);
            }
         }
      }
   ' ./Makefile.am > /tmp/samplicate-srcs
   
gcc -c $(cat /tmp/samplicate-srcs)

sed 's/\.c/\.o/' /tmp/samplicate-srcs > /tmp/samplicate-objs

gcc -o samplicate $(cat /tmp/samplicate-objs)
```

**Comment by bewing** [comment]
I used a standard bootstrap.sh file to handle the bootstrapping, and was able to build without issue.

**Comment by sleinen** [comment]
Sorry for the late reaction.  I used to distribute samplicator as an archive (samplicator-1.X.Y.tar.gz, can be created using `make dist` once you *have* a Makefile), which included the configure script.  But I didn't want to include the configure script in the Git repository.

I have now added some instructions to INSTALL.md (previously INSTALL) for compiling from source.  I also updated the automake input to work with newer versions of automake.

Can you check whether this works better?

**Comment by twopoint71** [comment]
Works perfectly.

# git clone https://github.com/sleinen/samplicator
# cd samplicator
# ./autogen.sh
# ./configure
# make
# cp ./samplicate /usr/local/bin/

**Comment by sleinen** [comment]
Thanks for testing!

In the meantime, I have also found that I can make "releases" on GitHub, and add "traditional" .tar.gz files to them.  These have been made using "make dist" and contain a generated `configure` script, so the original simple instructions should work there.

**Comment by sleinen** [comment]
I'm closing this issue, as I think it has been resolved by

a) [releases](https://github.com/sleinen/samplicator/releases) that include configure scripts, and
b) better installation documentation.

Feel free to reopen if you find this unsatisfactory.
