### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by geezyx** [sleinen/samplicator#31]
Hi there!  First, thank you for sharing this utility, it's really great!

I have noticed on a couple different VMs that I've tested this on (all building from latest source) that CPU utilization for a single core from the samplicate process is consuming ~90% CPU at all times, even with no data being sent to the service.  Is this expected behavior?  I haven't tried sending data to load it up yet.

Here are the flags I'm using:
```
/usr/local/bin/samplicate -S -f -p 2055 -c /etc/samplicator/samplicator.conf
```

And the config file:
```
# source/mask:destination/port
0.0.0.0/0.0.0.0:127.0.0.1/2055 10.5.2.39/2055 10.250.38.17/2055
```

**Comment by sleinen** [comment]
Sorry for the late response.  One problem with your command line is that you are looping packets back to the samplicator process via 127.0.0.1.  That would certainly explain very high CPU load, but only once the first packet is received.

**Comment by geezyx** [comment]
@sleinen oh my, that's a bit embarrassing!  I think I misunderstood the config file format in that case.  Just to confirm...

`# source/mask:destination/port`

I am now interpreting that as:

`<source/mask>:<space-delimited list of destination/port entries>`

Is that correct?  If so, is the source/mask also space delimited or is it one per line?

Thank you so much for the reply!

**Comment by geezyx** [comment]
I read the readme again (RTFM!) and this is pretty clear to me now...  Sorry for the trouble and I appreciate the reply.  Thank you again.
